server:
  port: 8081

spring:
  cloud:
    gateway:
      routes:
        - id: member-service
          uri: http://localhost:8080/
          predicates:
            - Path=/api/members/**
        - id: rune-service
          uri: http://localhost:8080/
          predicates:
            - Path=/api/runes/**